### ISSUE TITLE
iTransporter on Windows

### ISSUE THREAD

**Issue by elmo61** [sshaw/itunes_store_transporter#11]
This probably isn't really a issue per say but the documention looks out of date. I'm trying to get your repository working on windows but there is very little documentation to even download the correct transporter files that this repository needs.

I have downloaded iTMSTransporter_1.8.5.pkg but this doesn't seem the have the raw java files i would expect in it. is there somewhere else that contains the files we can use with this repository on windows.

**Comment by sshaw** [comment]
The [requirements section](https://github.com/sshaw/itunes_store_transporter#requirements) mentions that you need to install the Transporter. You should be able to download the Windows version by logging into iTunes Connect. Have you tried this?

Instructions can also be found in the Transporter User's Guide:

```
1. Click the Transporter link in the iTunes Connect home page.
iTunes Connect displays the Transporter Software and Documentation page with installation and
documentation downloads.
2. Click the Microsoft Windows XP link to download the installation package.
During install, Transporter automatically uninstalls your previous Transporter installation, registry key, and folders. To keep your earlier Transporter installation, rename the earlier installation directories before installing the current version.
3. Double-click the self-extracting installation executable (iTMSTransporterToolInstaller_1.8.3.exe) and follow the instructions that appear.
...
```

If the above does not work I would contact Apple. There is a Windows version.


I'm trying to avoid putting Apple's docs in `iTunes::Store::Transporter`'s docs. I assume that this installation information is readily available but installing on Windows does seems to cause problems for a lot of people so maybe I'll mention the above in the docs. What do you think?

**Comment by elmo61** [comment]
Yes, having logged into itunes connect there isnt any "Transporter link" on the ituens connect page, just my apps, app analytics etc etc closest is "resources and help" but that has a "Transporter User Guide" which is a pdf that has a direct link to downloading the Transporter for OSX at this link https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/resources/download/Transporter__OSX/bin
 no mention of windows in the document

**Comment by sshaw** [comment]
Maybe because your account is for Apps they assume that you can't use Windows since it doesn't support Xcode?

What's the version of the Transporter User Guide you have?

I would give you a link to the Windows exe but I no longer have an iTunes Connect account.

**Comment by elmo61** [comment]
its called "iTunes Connect Transporter Quick Start Guide v3" located here (https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/resources/download/TransporterQuickStartUserGuide/pdf) but i assume you cannot access if you dont have itunes connect any more.

**Comment by sshaw** [comment]
Ah, what I have is "iTunes Store Transporter User Guide"

**Comment by sshaw** [comment]
![transporter-win32](https://cloud.githubusercontent.com/assets/17570/8006880/a0f5cfce-0b65-11e5-987c-cb06b766bc61.png)

I'd contact Apple. Someone emailed me with the problem sometime ago. They were eventually able to download it. Let me try to find the email...

**Comment by elmo61** [comment]
Thanks, have done now. maybe they just simply don't want to advertise they have a windows version of the transporter file. 

Thanks for looking for the email!

**Comment by sshaw** [comment]
@elmo61 couldn't find that email. Any luck on your end?

**Comment by elmo61** [comment]
No luck so far. And no response from apple either!
