### ISSUE TITLE
Cannot use passwords with special characters

### ISSUE THREAD

**Issue by chappejw** [sshaw/itunes_store_transporter#13]
Using this tool, I cannot upload binaries if there are special characters in the password for the iTunesconnect user. Any solution? Dollar sign $ fails.

**Comment by sshaw** [comment]
Hi, please check to see if this is an issue with `iTMSTransporter`. Can you run the given command from the shell using your username and password? 

`iTMSTransporter` has been know to have [issues with shell metachars](https://github.com/sshaw/itunes_store_transporter/issues/12).

**Comment by chappejw** [comment]
This is an issue with iTMSTransporter. Likely this is a security precaution on Apple's part.

**Comment by sshaw** [comment]
> Likely this is a security precaution on Apple's part.

Heh, I assume it's because their wrapper script [does not escape shell metachars](https://github.com/sshaw/itunes_store_transporter/issues/12).
