### ISSUE TITLE
Hello！Which should I get open source used?

### ISSUE THREAD

**Issue by xhzengAIB** [sshaw/itunes_store_transporter#14]
Hi！@sshaw

Should I use this one? （https://github.com/sshaw/itunes_store_transporter 、https://github.com/sshaw/itunes_store_transporter_web）

What is the difference between the two it?

Jack

**Comment by sshaw** [comment]
> Should I use this one? 

It depends on your requirements. 

> What is the difference between the two it?

https://github.com/sshaw/itunes_store_transporter_web (Transporter GUI) is a UI for using the `iTMSTransporter`.  It makes it easy to deliver and manage your content on the iTunes Store. Check the features [here] (http://transportergui.com#features).

https://github.com/sshaw/itunes_store_transporter provides a Ruby API for using `iTMSTransporter`. 
Use it as you would any other API library. In general I'd say use it when you need to do something that cannot be done by the  [Transporter GUI](http://transportergui.com). 

It also comes with an "improved" version of the `iTMSTrasporter`, [`itms`](https://github.com/sshaw/itunes_store_transporter#using-itms).  You may find that better to use than the Transporter GUI.

**Comment by xhzengAIB** [comment]
@sshaw 
Thank you very much for your reply, we have been the main message.

Jack
